version: '3.9'
services:
  go-api:
    build: ./go-api
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  kotlin-api:
    build: ./kotlin-api
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M