name: Testar APIs com Docker Compose

on:
  push:
    branches:
      - main

jobs:
  test_apis:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/v2.10.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Construir imagens com Docker Compose
        run: |
          docker-compose build

      - name: Instalar wrk
        run: |
          sudo apt-get update
          sudo apt-get install -y wrk

      - name: Executar script de teste
        run: |
          chmod +x ./script.sh
          ./script.sh